### ISSUE TITLE
getBaseImageUrl is not aware of Cloudinary's automatic url encoding of asset names

### ISSUE THREAD

**Issue by frvge** [trivago/babel-plugin-cloudinary#7]
**Describe the bug**
Asset names with non-alphabetic characters get url-encoded by Cloudinary core. This is not taken into account in the `getBaseImageUrl` method, which produces unwanted results

**To Reproduce**
Use asset name "image_@2x.png" with getBaseImageUrl.
Result is like https://myurl/image_21%402x.png/image_@2x.png

**Expected behavior**
Return of the  getBaseImageUrl function is the baseurl with the "image_@2x.png" properly removed like Result is like https://myurl/

**Screenshots**
n/a

**Environment:**
-  node 11.14.0
-  npm 6.9.0
-  [cloudinary-core](https://github.com/cloudinary/pkg-cloudinary-core) 2.6.3

**Comments**
In `getBaseImageUrl` changing `return url.split(assetName)[0];` to `return url.split(encodeURIComponent(assetName))[0];` fixes this. I tried to capture it with a jest snapshot but couldn't.

**Comment by danielcaldas** [comment]
Fixed with the release of `babel-plugin-cloudinary@0.0.2`.
